### ISSUE TITLE
Changing font size in browser settings doesn't scale font.

### ISSUE THREAD

**Issue by HarlesPilter** [TEHIK-EE/tedi-design-system#155]
@airikej html tagile ei tohiks lükata fixed pixlites font size. oleks hea kui html tagil ei oleks üldse font-size määratud (Ainult % oleks ok). Kõige suurem element, millel see määratud võiks olla on body ja see peaks olema siis rem'ides. Seda sellepärast, et kui ma browseri settingute kaudu muudan font size suuremaks, 
![image](https://github.com/user-attachments/assets/061bd806-b543-4217-936d-cfce7532ecc0)
siis see sisuliselt lükkab html elemendile uue font-size. Kui meie aga oleme selle juba defineerinud siis sellel pole mingit effekti. Kui meie pole root font size määranud, siis see enamus browseritel on default 16px. 
![image](https://github.com/user-attachments/assets/4820dfb6-96ab-4352-aabd-6d230c5aec8b)

**Comment by airikej** [comment]
Tegin [PR](https://github.com/TEHIK-EE/tedi-design-system/pull/158) sellele
