### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by airikej** [TEHIK-EE/tedi-design-system#165]
- No API changes, would move from Community to Tedi-ready component
- Add unit test for Row and Col components
- Simplify story description and move documentation to ZeroHeight
- Replace and update Row and Col import paths in Community components

Later:
- Update Tedi-ready component stories with Row and Col components

**Comment by tarmokullas** [comment]
Would it be possible to make `<Col><Row>...</ Row></Col>` also work and be legible? Currently, there is a rule that Col has to be a direct child of Row.

I find `<Row direction="column"><Col>...</Col> </Row> ` to be a bit controversial since they switch meaning and make code reading worse.

**Comment by tarmokullas** [comment]
Okay, that makes sense. I've had to use Bootstrap very seldom, so I didn't know it was already set up there. Let's keep it as is, then. Thanks for the explanation!
