### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by airikej** [TEHIK-EE/tedi-design-system#166]
[Figma design](https://www.figma.com/design/jWiRIXhHRxwVdMSimKX2FF/%E2%9D%97TEDI-READY%E2%9D%97(follow-the-badges-in-header-to-see-which-components-are-ready-(designed%2Fdeveloped))?node-id=2405-49830&m=dev)

Community Tag component will break into 2 components: [Badge](https://github.com/orgs/TEHIK-EE/projects/9?pane=issue&itemId=75371934) and Tag:
- A badge is a status label that indicates the state of a process, person, document, or something similar. It provides the user with information about which stage the given process is in.
- A tag displays keywords, topics, applied filters, or other selections related to a document

New simplified Tag component would have API like this:

| Name | Required/Optional | Descrption | Type | Possible values | Default |
|----------|----------|----------|----------|----------|----------|
children | Required | Any content to be rendered within the tag component | `React.ReactNode \| React.ReactNode[]` | | |
className | Optional | Additional class name(s) to apply to the element | `string` | | |
onClose | Optional | Callback fired when the Tag close button is clicked | `MouseEventHandler<HTMLButtonElement>` | | |
isLoading | Optional | If Tag has loading state | `boolean` | | `false` |
hasError | Optional | Determines whether the Tag is in an error state. When true, the Tag will be styled accordingly and an error icon will be displayed. | `boolean` | | `false` |

**Comment by kasparsuvi1** [comment]
1. Should it also have isLoading property? For example if we want to use this new Tag in fileUpload, we should indicate how long the file is loading? (with spinner)
2.  will it be replaced in Community components? Which ones?

**Comment by airikej** [comment]
1. Sounds like a reasonable suggestion for me but have to discuss this with TEDI team
2. This component is tricky and can't be replaced so straight forwardly so we would have to leave Community-s Tag to Community right now and change them while we are bringing more components over to Tedi-ready

**Comment by karolin-kivisikk** [comment]
> 1. Should it also have isLoading property? For example if we want to use this new Tag in fileUpload, we should indicate how long the file is loading? (with spinner)
> 2. will it be replaced in Community components? Which ones?

@kasparsuvi1 you mean loader like this?

![Screenshot 2024-09-11 at 14 59 16](https://github.com/user-attachments/assets/7ac663c5-f9ae-4b4d-807a-cd041ea0bfec)

**Comment by airikej** [comment]
Upgraded the API regarding to isLoading prop

**Comment by airikej** [comment]
@HarlesPilter @kasparsuvi1 Do you think this component would benefit also from BreakpointSupport?

**Comment by kasparsuvi1** [comment]
Not really, becacuse there are none "visual" properties, that should change per breakpoint.
