### ISSUE TITLE
Skeleton

### ISSUE THREAD

**Issue by airikej** [TEHIK-EE/tedi-design-system#167]
Sõltuvus:
- VerticalSpacing

https://github.com/TEHIK-EE/tedi-design-system/issues/136

**Comment by airikej** [comment]
API changes:

Skeleton:
| Name | Required/Optional | Descrption | Type | Possible values | Default |
|----------|----------|----------|----------|----------|----------|
children | Required | PlaceholderBlocks content | `React.ReactNode \| React.ReactNode[]` | | |
className | Optional | Additional class name(s) to apply to the element | `string` | | |
label | Required | Accessibility label for screen-readers when component mounts and certain delay has passed. When omitted then info about all the skeletons currently on the page get combined into one info message. | `string` | | |
completedLabel | Required | Accessibility label for screen-readers that gets read when component unmounts. When label isn't read due to not meeting labelDelay requirement, then this props is ignored | `string` | | |
labelDelay | Optional | Callback fired when the Tag close button is clicked | `number` | | 1000ms  |

SkeletonBlock:
| Name | Required/Optional | Descrption | Type | Possible values | Default |
|----------|----------|----------|----------|----------|----------|
width | Optional | Width of the block in %. Defaults to width of the component | `number` | | 100 |
height | Optional | Height of the block. Defaults to line-height of paragraph - 'p' | `string` |  'p' \| 'h1' \| 'h2' \| 'h3' \| 'h4' \| 'h5' \| 'h6' \| number; | 'p' |
className | Optional | Additional class name(s) to apply to the element | `string` | | |
style | Optional | Custom style | `React.CSSProperties` | | |


Reasoning for changing label and completedLabel from optional > required:
- Consistent accessibility feedback
- Providing proper context
- Avoiding default messages

That doesn't mean LabelProvider will be removed from TEDI

**Comment by kasparsuvi1** [comment]
Is it now decided that label and completedLabel willl be required properties or is it still open?

**Comment by airikej** [comment]
Still open for discussion and suggestions!

**Comment by HarlesPilter** [comment]
I get that by turning the labels into required we are trying to get better accessibility messages for all the loaders. But by turning them into required doesn't necesserally guarantee a better outcome. 
Application devs can still set them label="", label="whatever" or label={some general translation that they use with all skeletons}. In the end it comes down to the application developer to provide a meaningful message with each Skeleton usage. And in my experience a lot of developers that either don't know much about accessibility or don't care enough will use exactly those options.

If we don't set them as required and provide a reasonable fallback translation we can at least guarantee, that if the application dev doesn't care enough and ignores setting a better label we provide a better result than label="" or label="whatever"

**Comment by airikej** [comment]
Will be waiting for TEHIK WCAG specialist comment on whether default labels are ok to use or need to be more contextual.
