### ISSUE TITLE
Text group

### ISSUE THREAD

**Issue by airikej** [TEHIK-EE/tedi-design-system#180]
https://github.com/TEHIK-EE/tedi-design-system/issues/140 

[Figma design](https://www.figma.com/design/jWiRIXhHRxwVdMSimKX2FF/%E2%9D%97TEDI-READY%E2%9D%97(follow-the-badges-in-header-to-see-which-components-are-ready-(designed%2Fdeveloped))?node-id=2137-19378&m=dev)

New text utility component and is used for e.g.:

- Displaying values
- - Document content values, including dates, locations, diagnoses, personal data, contact information, etc.
- Presenting terms and their definitions
- Clarifications of concepts
- Product or service specifications

| Name | Required/Optional | Descrption | Type | Possible values | Default |
|----------|----------|----------|----------|----------|----------|
label | Required | Label for the text group | `React.ReactNode` | | |
value | Required | Value displayed alongside the label | `React.ReactNode` | | |
className | Optional | Additional class name | `string` | | |
type | Optional | Type of text group layout | `TextGroupType` | `'vertical' \| 'horizontal'` | `'vertical'` |

**Comment by HarlesPilter** [comment]
- Is the vertical spacing between the label + value pairs handled by the developer using for example VerticalSpacing?
- Reading zeroheights then there should be a prop that controls the width of the label (For horizontal type)
- Type should probably be with breakpoint support
- What semantic element are we planning on using?

**Comment by airikej** [comment]
You ask the right questions - setting API before actually developing a component is tricky and will bring up changes to the API.

- I agree that VerticalSpacing would be indeed useful for controlling the vertical spacing - much like in List component right now.
- Yes, width prop is needed and will be added
- type prop was meant to have breakpoint support
- The idea was to use definition list semantic element (dl, dd, dt)

Suggestions and ideas are welcome
