### ISSUE TITLE
FormLabel

### ISSUE THREAD

**Issue by airikej** [TEHIK-EE/tedi-design-system#181]
https://github.com/TEHIK-EE/tedi-design-system/issues/142 

Mostly unchanged from Community's FormLabel

| Name | Required/Optional | Description | Type | Possible values | Default |
|----------|----------|----------|----------|----------|----------|
label | Required | Label value | `string` | | |
id | Required | ID of element label is for | `string` | | |
className | Optional | Additional class name | `string` | | |
required | Optional | Renders required symbol | `boolean` | | `false` |
requiredLabel | Optional | Label shown when input is required | `string` | | |
hideLabel | Optional | Whether to hide the label visually. Use keep-space to save label space | `boolean \| 'keep-space'` | | `false` |
renderWithoutLabel | Optional | Render without label HTML element - used when Form component uses label inside already | `boolean` | | `false` |

**Need clarifying:**

- `size` prop - In Community's FormLabel there is a size prop, that has values: `'small' | 'default' | 'large'` and `size` prop is only used inside TextField and NumberField components. Is it realistically needed? Where would you use large sized FormLabel?
- Would you benefit from `isBold` prop? It would render the label as bold.

**Comment by kasparsuvi1** [comment]
`size` - smaller inputs would have smaller labels. So when u use select or textfield that is size="small". Then the label would be smaller in size also (atleast with previous design)

`isBold` - It's question to design, should there be possibility to use bold label on form elements? I dont think so, atleast currently i don't know use-case where it should be needed. And it doesn't hold applications with one style imo.

**Comment by HarlesPilter** [comment]
We use large TextField in Terviseportaal digital-registry flow
![image](https://github.com/user-attachments/assets/819c2fdb-3a58-4396-9d0d-3c638f06e67c)

**Comment by airikej** [comment]
@karolin-kivisikk It appears all sizes are in use, including large.

**Comment by karolin-kivisikk** [comment]
> @karolin-kivisikk It appears all sizes are in use, including large.

* Added small label size to Figma
* Added Large input size under [Search](https://www.figma.com/design/jWiRIXhHRxwVdMSimKX2FF/%E2%9D%97TEDI-READY%E2%9D%97(follow-the-badges-in-header-to-see-which-components-are-ready-(designed%2Fdeveloped))?node-id=4620-82860&t=cZyksISdQXcCpHW0-4) component
