### ISSUE TITLE
Separator

### ISSUE THREAD

**Issue by airikej** [TEHIK-EE/tedi-design-system#206]
[Figma](https://www.figma.com/design/jWiRIXhHRxwVdMSimKX2FF/%E2%9D%97TEDI-READY%E2%9D%97(follow-the-badges-in-header-to-see-which-components-are-ready-(designed%2Fdeveloped))?node-id=5797-116776&t=pQAO0g4IeKdgAGJz-4)

Component: Separator

`
export type SeparatorSpacing = {
  vertical?: VerticalSpacingSize;
  top?: VerticalSpacingSize;
  bottom?: VerticalSpacingSize;
};
`

| Name | Required/Optional | Description | Type | Possible values | Default |
|----------|----------|----------|----------|----------|----------|
as | Optional | The HTML element used to render the separator (e.g., hr, div, or span). | `SeparatorElement ` | `'div' \| 'span' \| 'hr'` | `'div'` |
stretch | Optional | Whether the separator should stretch to fill the full width of its container | `boolean` | |  `false` |
className | Optional | Additional class applied to the element. | `string` | | |
spacing | Optional | Defines the spacing around the separator. The object can specify vertical spacing (applied to both top and bottom) or individual top and bottom spacings. If vertical is provided, it overrides top and bottom. The values correspond to em units. | `SeparatorSpacing` |  `0 \| 0.25 \| 0.5 \| 0.75 \| 1 \| 1.25 \| 1.5 \| 1.75 \| 2 \| 2.5 \| 5` | `0.25` |
axis | Optional | Defines whether the separator is horizontal or vertical. | `SeparatorAxis` |  `'horizontal' \| 'vertical'` | `horizontal` |
color | Optional | Color of separator | `SeparatorColor` |  `'primary' \| 'secondary' \| 'accent'` | `primary` |
variant | Optional | Style variant of the separator (e.g., dotted or dotted-small) | `SeparatorVariant` |  `'dotted' \| 'dotted-small'` | |
thickness | Optional | The thickness of the separator in pixels. Ignored if `styleVariant` is used. Defaults to 1px. | `1 \| 2` | | `1` |

- Use VerticalSpacing components Size values
- BreakpointSupport on spacing, isFullWidth, axis, color, styleVariant and thickness
- Improve naming of the props for common naming practices and clarity
- Add unit test

**Comment by kasparsuvi1** [comment]
`isFullWidth` descriptions is wrong - It does not stretch to fill the full width of its container. Its stretches only when its used inside Card component and is directly depended on it.

`spacing` - should also accept only numeric values. Because alot of times vertical spacing is wanted. And then the developer doesnt always need to pass a full object, but also can pass just a number. (Same logic is used inside Grid)

`color` - im not liking that using "primary" color is primary-border-color in reality. Should look over how to name color options in all the components.

**Comment by HarlesPilter** [comment]
- `isFullWidth` naming is very specific to `axis="horizontal"`. Maybe we should rename this or at least improve the prop description.
- `spacing` - When setting separate top and bottom spacing then for `axis="vertical"` they should also add margin to top/bottom.
