### ISSUE TITLE
Text field

### ISSUE THREAD

**Issue by airikej** [TEHIK-EE/tedi-design-system#234]
https://github.com/TEHIK-EE/tedi-design-system/issues/119 

[Figma](https://www.figma.com/design/jWiRIXhHRxwVdMSimKX2FF/%E2%9D%97TEDI-READY%E2%9D%97(follow-the-badges-in-header-to-see-which-components-are-ready-(designed%2Fdeveloped))?node-id=3486-37651&m=dev)

Dependencies:
- FormLabel
- Button
- Icon
- Separator

No API changes but would suggest this:
- Merge `onChange` and `onChangeEvent`: This can simplify the API by having a single prop that supports both use cases.
- Add unit tests

**Comment by kasparsuvi1** [comment]
> Merge onChange and onChangeEvent: This can simplify the API by having a single prop that supports both use cases.
Most common cases use onChange, because there is nothing else but value needed from the event.
But there are some usecases where event is needed, for that purpose i think both should be available.

**Comment by airikej** [comment]
@kasparsuvi1 @HarlesPilter is TextField with clearing button used anywhere else than just as search input? The designers want to break them into 2 components, so TextField wouldn't be having either large variant and also clearable button - they would be exclusive to Search component later. What do you think about that?
