### ISSUE TITLE
Tüpograafia: line-height

### ISSUE THREAD

**Issue by karolinkk** [TEHIK-EE/tedi-design-system#29]
**Tüüp**: Täiendus
**Autor**: Alina Trussova
**Seotud komponendid**: -
**Figma**: [link](https://www.figma.com/file/xK5lP0Qaf3KjxS2YsuVUND/typography?type=design&node-id=26%3A79696&mode=design&t=j8e7sjfBVjZGJLHF-1)

## Probleem
Terviseportaalis on mobiiliversiooni reakõrgused olnud pikalt probleemiks. Hetkel on liiga õhuline (kõik 150%) ja vajab palju õhku. Samal ajal kasutajatelt saame palju tagasisidet, et nad eelistavad kompaktsust, mida ei ole võimalik saavutada ainult paddingu vähendamisega ilma reavahede korrastamiseta. Kuna ülevaatlikus on TPs oluline, soovime seda võimaluselt sel nädalal täiendada. 

## Eesmärk
Vähendada tüpograafia line-heighti selliselt et mobiilis poleks nii palju tühja ruumi elementide ja pealkirjade vahel.

## Kirjeldus
Pakun järgmist lähenemist:
* Heading'ud teha kompaktsemaks.
* Vaatasin need üle ka VEERA 1.0.0. versiooni. Seal on kasutatud sarnast loogikat.
* Disainisin nii, et samal fondi suurusel nii suurel ekraanil kui ka mobiilis olema sama reakõrgus, et vältida konflikte.
* Reakõrgus on Terviseportaali näitel testitud ja valitud selline, mis töötaks optimaalselt nii kitsa kui ka laia rea pikkuse puhul (ehk desktop/mobiil ja suur konteiner/kitsas konteiner)
* H1 on veidi õhulisem, kui teised, kuna „light“ stiil vajab natuke rohkem hingamisruumi. Siiski sooviksin seal ka 2px vähem, et see toimiks paremini väiksemate rea pikkustega (näiteks TP töölaual).

![Screenshot 2024-04-28 at 15 07 58 (1)](https://github.com/TEHIK-EE/tedi-design-system/assets/28707194/c96c6076-d7fb-454f-97b1-6a67b89f844d)
![Screenshot 2024-04-28 at 15 08 25 (1)](https://github.com/TEHIK-EE/tedi-design-system/assets/28707194/5a1c0a90-7462-4e98-98ab-a41cfad640c3)

## Kasutusala
Mobiil, väiksed seadmed, vaated kus tabeli vajadus

## Lahtised küsimused
* Kas fondi suurused tuginevad pigem Veerale või Tehiku disainisüsteemile?

## Teha vaja
* TEDI-s tüpo luua
* testimine
* arendus

**Comment by karolin-kivisikk** [comment]
Communitys said parandused tehtud, TEDI-s sai tehtud uuendused vastu Community muudatusi.
