### ISSUE TITLE
Number input

### ISSUE THREAD

**Issue by airikej** [TEHIK-EE/tedi-design-system#309]
https://github.com/TEHIK-EE/tedi-design-system/issues/126 

[Figma](https://www.figma.com/design/jWiRIXhHRxwVdMSimKX2FF/TEDI-READY-(work-in-progress)?node-id=4536-78765&m=dev)

Current plans:
- Add unit test
- Fix bugs (mentioned in the comments)
- Documentation to ZeroHeight

**Comment by tarmokullas** [comment]
NumberField has following bugs.

**If min or max is set to 0, then it is treated as false value**
![Image](https://github.com/user-attachments/assets/53dd5ac8-1f42-4924-8f8c-d1cb25acefd1)

Should be 
```typescript
const isBelowMinValue = Boolean(min !== undefined && currentValue < min);
const isAboveMaxValue = Boolean(max !== undefined && currentValue > max);
``` 

**NumberField has no background, like other inputs seem to have by default**
![Image](https://github.com/user-attachments/assets/fca399a0-0582-468b-988f-6f0b98ed7c5b)
