### ISSUE TITLE
[Alert]: Content only alignment

### ISSUE THREAD

**Issue by HarlesPilter** [TEHIK-EE/tedi-design-system#320]
When there is no title, there is a noticable shift in vertical alignment

![image](https://github.com/user-attachments/assets/9aa47fbd-f104-4e6e-912b-1a40c852dda2)

Seems to be that VerticalSpacing adds margin bottom to all children, but last element shouldn't need one

![image](https://github.com/user-attachments/assets/0cf4f29c-8093-4622-9535-b348439731ed)

**Comment by HarlesPilter** [comment]
Win + 131.0.6778.86 Chrome. Still there. Best visible with this story: https://github.tehik.ee/tedi-design-system/rc/?path=/docs/tedi-ready-components-notifications-alert--docs#alert%20colors

**Comment by airikej** [comment]
Thank you, will check it out
