### ISSUE TITLE
Revise BEM classes on TEDI-Ready components

### ISSUE THREAD

**Issue by airikej** [TEHIK-EE/tedi-design-system#328]
## Problem:

Some components have improper BEM class namings e.g `tedi-icon--wrapper`, `tedi-status-badge--filled-bordered--success`

## Acceptance:

All classes should follow BEM guidelines and be e.g `tedi-icon__wrapper` instead

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the class names in icon.module.scss and status-badge.module.scss to follow BEM naming conventions. Changed double-dash separators to single underscores for elements and double underscores for modifiers. Ensured that the functionality and styling remain the same.

You can review changes in this commit: https://github.com/lkilu6456546/TEHIK-EE-tedi-design-system-328/commit/ccc437693afe8438813e61c494707ab77fa42293.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
