### ISSUE TITLE
[Grid]: <Row> working differently, when cols value is bigger than 6

### ISSUE THREAD

**Issue by tarmokullas** [TEHIK-EE/tedi-design-system#345]
**Tarmo K:**

> Kui cols väärtus on vahemikus 1-6, siis jäävad täitmata veerud ootuspäraselt tühjaks.
> ```
> <Row cols={4} wrap="nowrap">
>   <Col>Element1</Col>
>   <Col>Element1</Col>
> </Row>
> ```
> Kaks elementi on paigutatud veergudusse 1 ja 2, veerud 3 ja 4 on ootuspäraselt tühjad.
> 
> ![image](https://github.com/user-attachments/assets/b0630a2f-8a0a-4723-83ff-927263a90714)
> 
> Kui cols väärtus on vahemikus 7-12, siis jagunevad elemendid võrdselt kogu ala peale ära. Tühje veerge ei jää.
> ```
> <Row cols={7} wrap="nowrap">
>   <Col>Element1</Col>
>   <Col>Element1</Col>
> </Row>
> ```
> Eeldaks, et Element1 ja Element2 oleks kuvatud veergudes 1 ja 2, ning veerud 3-7 oleks tühjad.
> 
> ![image](https://github.com/user-attachments/assets/260399dc-7883-4296-8f83-349e1a2f24e7)

**Hannes-Herman P:**

> Mulle tundub, et bugi. kui cols=6, siis saavad colsid külge klassi. 
> 
> ![image](https://github.com/user-attachments/assets/116f910a-506f-44f2-8653-46c10e5b5b18)
> 
> Kui cols=7, siis sarnast klassi ei lisata
> https://github.com/TEHIK-EE/tedi-design-system/blob/rc/libs/react-components/src/shared/styles/variables/_bootstrap-variables.scss#L3C1-L3C22
> 
> millegipärast bootstrapil endal ka seal 6 https://getbootstrap.com/docs/5.3/layout/grid/#sass-variables
>

**Comment by airikej** [comment]
I looked into it and setting `$grid-row-columns:  6;` indeed fixes that problem. The only downside is that Boostraps CSS bundle will increase a little bit.

What do you think @HarlesPilter @tarmokullas  should I implement this change?

**Comment by HarlesPilter** [comment]
I wouldn't set it 12, as then it would work as a normal grid. I see 2 options:

1. Set it as 11
2. Keep it at 6, but limit the prop type to 6 as well and add a comment why we support only 6

**Comment by tarmokullas** [comment]
I get that 12 and 11 end up producing the same result, but I don't get why 11 is better than 12. Saves bundle size? Isn't the main point of the `cols` prop to make it work like a grid? And maybe one less question less in the future when someone sees the rather unexpected value 11.
