### ISSUE TITLE
[ScrollFade]: ScrollFade doesn't always trigger scrollToBottom

### ISSUE THREAD

**Issue by kasparsuvi1** [TEHIK-EE/tedi-design-system#353]
## Problem
On some cases element.scrollTop is not integer and so we don't trigger `onScrollToBottom` correctly

## Solution
Add some tolerance to rounding, it should be OK to trigger it 1-2px before user actually is scrolled to the bottom.

## example
![image](https://github.com/user-attachments/assets/5cb13888-1c69-43e1-9649-07030b4abb1c)

**Comment by HarlesPilter** [comment]
I wonder why this didn't automatically close
